[package]
name = "d-didgin-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-land.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14"
rand = "0.8.5"